/*
 Do not modify, auto-generated by model_gen.tcl

 Copyright 2019 Alain Dargelas

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

/*
 * File:   enum_struct_union_packed_var_group.h
 * Author:
 *
 * Created on December 14, 2019, 10:03 PM
 */

#ifndef ENUM_STRUCT_UNION_PACKED_VAR_GROUP_H
#define ENUM_STRUCT_UNION_PACKED_VAR_GROUP_H

namespace UHDM {

  bool enum_struct_union_packed_var_groupGroupCompliant(any* item);
  bool enum_struct_union_packed_var_groupGroupCompliant(VectorOfany* vec);
 	     
};

#endif

