/*
 Do not modify, auto-generated by model_gen.tcl

 Copyright 2019 Alain Dargelas

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

/*
 * File:   expr_dist.h
 * Author:
 *
 * Created on December 14, 2019, 10:03 PM
 */

#ifndef EXPR_DIST_H
#define EXPR_DIST_H

namespace UHDM {

  class expr_dist : public BaseClass {
  public:
    // Implicit constructor used to initialize all members,
    // comment: expr_dist();
    ~expr_dist()  {}
    
    virtual unsigned int getUhdmType() { return uhdmexpr_dist; }   
  private:
    
  };

  class expr_distFactory {
  friend Serializer;
  public:
  static expr_dist* make() {
    expr_dist* obj = new expr_dist();
    objects_.push_back(obj);
    return obj;
  }
  private:
    static std::vector<expr_dist*> objects_;
  };
 	      
  class VectorOfexpr_distFactory {
  friend Serializer;
  public:
  static std::vector<expr_dist*>* make() {
    std::vector<expr_dist*>* obj = new std::vector<expr_dist*>();
    objects_.push_back(obj);
    return obj;
  }
  private:
  static std::vector<std::vector<expr_dist*>*> objects_;
  };

};

#endif

