/*
 Do not modify, auto-generated by model_gen.tcl

 Copyright 2019 Alain Dargelas

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

/*
 * File:   forks.h
 * Author:
 *
 * Created on December 14, 2019, 10:03 PM
 */

#ifndef FORKS_H
#define FORKS_H

namespace UHDM {

  class forks : public scope {
  public:
    // Implicit constructor used to initialize all members,
    // comment: forks();
    ~forks() final {}
    
    BaseClass* get_vpiParent() const { return vpiParent_; }

    void set_vpiParent(BaseClass* data) { vpiParent_ = data; }

    unsigned int get_uhdmParentType() const { return uhdmParentType_; }

    void set_uhdmParentType(unsigned int data) { uhdmParentType_ = data; }

    std::string get_vpiFile() const { return SymbolFactory::getSymbol(vpiFile_); }

    void set_vpiFile(std::string data) { vpiFile_ = SymbolFactory::make(data); }

    unsigned int get_vpiLineNo() const { return vpiLineNo_; }

    void set_vpiLineNo(unsigned int data) { vpiLineNo_ = data; }

    int get_vpiJoinType() const { return vpiJoinType_; }

    void set_vpiJoinType(int data) { vpiJoinType_ = data; }

    virtual unsigned int getUhdmType() { return uhdmforks; }   
  private:
    
    BaseClass* vpiParent_;

    unsigned int uhdmParentType_;

    unsigned int vpiFile_;

    unsigned int vpiLineNo_;

    int vpiJoinType_;

  };

  class forksFactory {
  friend Serializer;
  public:
  static forks* make() {
    forks* obj = new forks();
    objects_.push_back(obj);
    return obj;
  }
  private:
    static std::vector<forks*> objects_;
  };
 	      
  class VectorOfforksFactory {
  friend Serializer;
  public:
  static std::vector<forks*>* make() {
    std::vector<forks*>* obj = new std::vector<forks*>();
    objects_.push_back(obj);
    return obj;
  }
  private:
  static std::vector<std::vector<forks*>*> objects_;
  };

};

#endif

