/*
 Do not modify, auto-generated by model_gen.tcl

 Copyright 2019 Alain Dargelas

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

/*
 * File:   interface.h
 * Author:
 *
 * Created on December 14, 2019, 10:03 PM
 */

#ifndef INTERFACE_H
#define INTERFACE_H

namespace UHDM {

  class interface : public instance {
  public:
    // Implicit constructor used to initialize all members,
    // comment: interface();
    ~interface() final {}
    
    BaseClass* get_vpiParent() const { return vpiParent_; }

    bool set_vpiParent(BaseClass* data) { vpiParent_ = data; return true;}

    unsigned int get_uhdmParentType() const { return uhdmParentType_; }

    bool set_uhdmParentType(unsigned int data) { uhdmParentType_ = data; return true;}

    std::string get_vpiFile() const { return SymbolFactory::getSymbol(vpiFile_); }

    bool set_vpiFile(std::string data) { vpiFile_ = SymbolFactory::make(data); return true; }

    unsigned int get_vpiLineNo() const { return vpiLineNo_; }

    bool set_vpiLineNo(unsigned int data) { vpiLineNo_ = data; return true;}

    unsigned int get_vpiIndex() const { return vpiIndex_; }

    bool set_vpiIndex(unsigned int data) { vpiIndex_ = data; return true;}

    unsigned int get_vpiType() { return vpiInterface; }

    expr_dist* get_expr_dist() const { return expr_dist_; }

    bool set_expr_dist(expr_dist* data) { expr_dist_ = data; return true;}

    instance_array* get_instance_array() const { return instance_array_; }

    bool set_instance_array(instance_array* data) { instance_array_ = data; return true;}

    VectorOfprocess* get_process() const { return process_; }

    bool set_process(VectorOfprocess* data) { process_ = data; return true;}

    VectorOfinterface_tf_decl* get_interface_tf_decls() const { return interface_tf_decls_; }

    bool set_interface_tf_decls(VectorOfinterface_tf_decl* data) { interface_tf_decls_ = data; return true;}

    VectorOfmodport* get_modports() const { return modports_; }

    bool set_modports(VectorOfmodport* data) { modports_ = data; return true;}

    clocking_block* get_global_clocking() const { return global_clocking_; }

    bool set_global_clocking(clocking_block* data) { global_clocking_ = data; return true;}

    clocking_block* get_default_clocking() const { return default_clocking_; }

    bool set_default_clocking(clocking_block* data) { default_clocking_ = data; return true;}

    VectorOfmod_path* get_mod_paths() const { return mod_paths_; }

    bool set_mod_paths(VectorOfmod_path* data) { mod_paths_ = data; return true;}

    VectorOfcont_assign* get_cont_assigns() const { return cont_assigns_; }

    bool set_cont_assigns(VectorOfcont_assign* data) { cont_assigns_ = data; return true;}

    VectorOfinterface* get_interfaces() const { return interfaces_; }

    bool set_interfaces(VectorOfinterface* data) { interfaces_ = data; return true;}

    VectorOfinterface_array* get_interface_arrays() const { return interface_arrays_; }

    bool set_interface_arrays(VectorOfinterface_array* data) { interface_arrays_ = data; return true;}

    virtual unsigned int getUhdmType() { return uhdminterface; }   
  private:
    
    BaseClass* vpiParent_;

    unsigned int uhdmParentType_;

    unsigned int vpiFile_;

    unsigned int vpiLineNo_;

    unsigned int vpiIndex_;

    expr_dist* expr_dist_;

    instance_array* instance_array_;

    VectorOfprocess* process_;

    VectorOfinterface_tf_decl* interface_tf_decls_;

    VectorOfmodport* modports_;

    clocking_block* global_clocking_;

    clocking_block* default_clocking_;

    VectorOfmod_path* mod_paths_;

    VectorOfcont_assign* cont_assigns_;

    VectorOfinterface* interfaces_;

    VectorOfinterface_array* interface_arrays_;

  };

  class interfaceFactory {
  friend Serializer;
  public:
  static interface* make() {
    interface* obj = new interface();
    objects_.push_back(obj);
    return obj;
  }
  private:
    static std::vector<interface*> objects_;
  };
 	      
  class VectorOfinterfaceFactory {
  friend Serializer;
  public:
  static std::vector<interface*>* make() {
    std::vector<interface*>* obj = new std::vector<interface*>();
    objects_.push_back(obj);
    return obj;
  }
  private:
  static std::vector<std::vector<interface*>*> objects_;
  };

};

#endif

