/*
 Do not modify, auto-generated by model_gen.tcl

 Copyright 2019 Alain Dargelas

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

/*
 * File:   net_drivers.h
 * Author:
 *
 * Created on December 14, 2019, 10:03 PM
 */

#ifndef NET_DRIVERS_H
#define NET_DRIVERS_H

namespace UHDM {

  class net_drivers : public BaseClass {
  public:
    // Implicit constructor used to initialize all members,
    // comment: net_drivers();
    ~net_drivers()  {}
    
    virtual unsigned int getUhdmType() { return uhdmnet_drivers; }   
  private:
    
  };

  class net_driversFactory {
  friend Serializer;
  public:
  static net_drivers* make() {
    net_drivers* obj = new net_drivers();
    objects_.push_back(obj);
    return obj;
  }
  private:
    static std::vector<net_drivers*> objects_;
  };
 	      
  class VectorOfnet_driversFactory {
  friend Serializer;
  public:
  static std::vector<net_drivers*>* make() {
    std::vector<net_drivers*>* obj = new std::vector<net_drivers*>();
    objects_.push_back(obj);
    return obj;
  }
  private:
  static std::vector<std::vector<net_drivers*>*> objects_;
  };

};

#endif

