/*
 Do not modify, auto-generated by model_gen.tcl

 Copyright 2019 Alain Dargelas

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

/*
 * File:   operation.h
 * Author:
 *
 * Created on December 14, 2019, 10:03 PM
 */

#ifndef OPERATION_H
#define OPERATION_H

namespace UHDM {

  class operation : public expr {
  public:
    // Implicit constructor used to initialize all members,
    // comment: operation();
    ~operation() final {}
    
    BaseClass* get_vpiParent() const { return vpiParent_; }

    void set_vpiParent(BaseClass* data) { vpiParent_ = data; }

    unsigned int get_uhdmParentType() const { return uhdmParentType_; }

    void set_uhdmParentType(unsigned int data) { uhdmParentType_ = data; }

    std::string get_vpiFile() const { return SymbolFactory::getSymbol(vpiFile_); }

    void set_vpiFile(std::string data) { vpiFile_ = SymbolFactory::make(data); }

    unsigned int get_vpiLineNo() const { return vpiLineNo_; }

    void set_vpiLineNo(unsigned int data) { vpiLineNo_ = data; }

    int get_vpiOpType() const { return vpiOpType_; }

    void set_vpiOpType(int data) { vpiOpType_ = data; }

    VectorOfoperand_group* get_operands() const { return operands_; }

    bool set_operands(VectorOfoperand_group* data) { operands_ = data; return true;}

    unsigned int get_vpiType() { return vpiOperation; }

    virtual unsigned int getUhdmType() { return uhdmoperation; }   
  private:
    
    BaseClass* vpiParent_;

    unsigned int uhdmParentType_;

    unsigned int vpiFile_;

    unsigned int vpiLineNo_;

    int vpiOpType_;

    VectorOfoperand_group* operands_;

  };

  class operationFactory {
  friend Serializer;
  public:
  static operation* make() {
    operation* obj = new operation();
    objects_.push_back(obj);
    return obj;
  }
  private:
    static std::vector<operation*> objects_;
  };
 	      
  class VectorOfoperationFactory {
  friend Serializer;
  public:
  static std::vector<operation*>* make() {
    std::vector<operation*>* obj = new std::vector<operation*>();
    objects_.push_back(obj);
    return obj;
  }
  private:
  static std::vector<std::vector<operation*>*> objects_;
  };

};

#endif

