/*
 Do not modify, auto-generated by model_gen.tcl

 Copyright 2019 Alain Dargelas

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

/*
 * File:   packed_array_var.h
 * Author:
 *
 * Created on December 14, 2019, 10:03 PM
 */

#ifndef PACKED_ARRAY_VAR_H
#define PACKED_ARRAY_VAR_H

namespace UHDM {

  class packed_array_var : public variables {
  public:
    // Implicit constructor used to initialize all members,
    // comment: packed_array_var();
    ~packed_array_var() final {}
    
    BaseClass* get_vpiParent() const { return vpiParent_; }

    bool set_vpiParent(BaseClass* data) { vpiParent_ = data; return true;}

    unsigned int get_uhdmParentType() const { return uhdmParentType_; }

    bool set_uhdmParentType(unsigned int data) { uhdmParentType_ = data; return true;}

    std::string get_vpiFile() const { return SymbolFactory::getSymbol(vpiFile_); }

    bool set_vpiFile(std::string data) { vpiFile_ = SymbolFactory::make(data); return true; }

    unsigned int get_vpiLineNo() const { return vpiLineNo_; }

    bool set_vpiLineNo(unsigned int data) { vpiLineNo_ = data; return true;}

    expr* get_left_expr() const { return left_expr_; }

    bool set_left_expr(expr* data) { left_expr_ = data; return true;}

    expr* get_right_expr() const { return right_expr_; }

    bool set_right_expr(expr* data) { right_expr_ = data; return true;}

    VectorOfrange* get_ranges() const { return ranges_; }

    bool set_ranges(VectorOfrange* data) { ranges_ = data; return true;}

    VectorOfvar_bit* get_var_bits() const { return var_bits_; }

    bool set_var_bits(VectorOfvar_bit* data) { var_bits_ = data; return true;}

    unsigned int get_vpiType() { return vpiPackedArrayVar; }

    virtual unsigned int getUhdmType() { return uhdmpacked_array_var; }   
  private:
    
    BaseClass* vpiParent_;

    unsigned int uhdmParentType_;

    unsigned int vpiFile_;

    unsigned int vpiLineNo_;

    expr* left_expr_;

    expr* right_expr_;

    VectorOfrange* ranges_;

    VectorOfvar_bit* var_bits_;

  };

  class packed_array_varFactory {
  friend Serializer;
  public:
  static packed_array_var* make() {
    packed_array_var* obj = new packed_array_var();
    objects_.push_back(obj);
    return obj;
  }
  private:
    static std::vector<packed_array_var*> objects_;
  };
 	      
  class VectorOfpacked_array_varFactory {
  friend Serializer;
  public:
  static std::vector<packed_array_var*>* make() {
    std::vector<packed_array_var*>* obj = new std::vector<packed_array_var*>();
    objects_.push_back(obj);
    return obj;
  }
  private:
  static std::vector<std::vector<packed_array_var*>*> objects_;
  };

};

#endif

