/*
 Do not modify, auto-generated by model_gen.tcl

 Copyright 2019 Alain Dargelas

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

/*
 * File:   process.h
 * Author:
 *
 * Created on December 14, 2019, 10:03 PM
 */

#ifndef PROCESS_H
#define PROCESS_H

namespace UHDM {

  class process : public BaseClass {
  public:
    process(){}
    ~process() final {}
    
    BaseClass* get_vpiParent() const { return vpiParent_; }

    void set_vpiParent(BaseClass* data) { vpiParent_ = data; }

    int get_uhdmParentType() const { return uhdmParentType_; }

    void set_uhdmParentType(int data) { uhdmParentType_ = data; }

    std::string get_vpiFile() const { return SymbolFactory::getSymbol(vpiFile_); }

    void set_vpiFile(std::string data) { vpiFile_ = SymbolFactory::make(data); }

    int get_vpiLineNo() const { return vpiLineNo_; }

    void set_vpiLineNo(int data) { vpiLineNo_ = data; }

  private:
    
    BaseClass* vpiParent_;

    int uhdmParentType_;

    unsigned int vpiFile_;

    int vpiLineNo_;

  };

  class processFactory {
  friend Serializer;
  public:
  static process* make() {
    process* obj = new process();
    objects_.push_back(obj);
    return obj;
  }
  private:
    static std::vector<process*> objects_;
  };
 	      
  class VectorOfprocessFactory {
  friend Serializer;
  public:
  static std::vector<process*>* make() {
    std::vector<process*>* obj = new std::vector<process*>();
    objects_.push_back(obj);
    return obj;
  }
  private:
  static std::vector<std::vector<process*>*> objects_;
  };

};

#endif

