/*
 Do not modify, auto-generated by model_gen.tcl

 Copyright 2019 Alain Dargelas

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

/*
 * File:   scope.h
 * Author:
 *
 * Created on December 14, 2019, 10:03 PM
 */

#ifndef SCOPE_H
#define SCOPE_H

namespace UHDM {

  class scope : public BaseClass {
  public:
    scope(){}
    ~scope()  {}
    
    std::string get_vpiName() const { return SymbolFactory::getSymbol(vpiName_); }

    void set_vpiName(std::string data) { vpiName_ = SymbolFactory::make(data); }

    std::string get_vpiFullName() const { return SymbolFactory::getSymbol(vpiFullName_); }

    void set_vpiFullName(std::string data) { vpiFullName_ = SymbolFactory::make(data); }

    virtual unsigned int getUhdmType() { return uhdmscope; }   
  private:
    
    unsigned int vpiName_;

    unsigned int vpiFullName_;

  };

  class scopeFactory {
  friend Serializer;
  public:
  static scope* make() {
    scope* obj = new scope();
    objects_.push_back(obj);
    return obj;
  }
  private:
    static std::vector<scope*> objects_;
  };
 	      
  class VectorOfscopeFactory {
  friend Serializer;
  public:
  static std::vector<scope*>* make() {
    std::vector<scope*>* obj = new std::vector<scope*>();
    objects_.push_back(obj);
    return obj;
  }
  private:
  static std::vector<std::vector<scope*>*> objects_;
  };

};

#endif

