/*
 Do not modify, auto-generated by model_gen.tcl

 Copyright 2019 Alain Dargelas

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

/*
 * File:   struct_var.h
 * Author:
 *
 * Created on December 14, 2019, 10:03 PM
 */

#ifndef STRUCT_VAR_H
#define STRUCT_VAR_H

namespace UHDM {

  class struct_var : public variables {
  public:
    // Implicit constructor used to initialize all members,
    // comment: struct_var();
    ~struct_var() final {}
    
    BaseClass* get_vpiParent() const { return vpiParent_; }

    bool set_vpiParent(BaseClass* data) { vpiParent_ = data; return true;}

    unsigned int get_uhdmParentType() const { return uhdmParentType_; }

    bool set_uhdmParentType(unsigned int data) { uhdmParentType_ = data; return true;}

    std::string get_vpiFile() const { return SymbolFactory::getSymbol(vpiFile_); }

    bool set_vpiFile(std::string data) { vpiFile_ = SymbolFactory::make(data); return true; }

    unsigned int get_vpiLineNo() const { return vpiLineNo_; }

    bool set_vpiLineNo(unsigned int data) { vpiLineNo_ = data; return true;}

    bool get_vpiPackedArrayMember() const { return vpiPackedArrayMember_; }

    bool set_vpiPackedArrayMember(bool data) { vpiPackedArrayMember_ = data; return true;}

    bool get_vpiConstantSelect() const { return vpiConstantSelect_; }

    bool set_vpiConstantSelect(bool data) { vpiConstantSelect_ = data; return true;}

    VectorOfvariables* get_variables() const { return variables_; }

    bool set_variables(VectorOfvariables* data) { variables_ = data; return true;}

    expr* get_expr_index() const { return expr_index_; }

    bool set_expr_index(expr* data) { expr_index_ = data; return true;}

    VectorOfvar_bit* get_var_bits() const { return var_bits_; }

    bool set_var_bits(VectorOfvar_bit* data) { var_bits_ = data; return true;}

    unsigned int get_vpiType() { return vpiStructVar; }

    virtual unsigned int getUhdmType() { return uhdmstruct_var; }   
  private:
    
    BaseClass* vpiParent_;

    unsigned int uhdmParentType_;

    unsigned int vpiFile_;

    unsigned int vpiLineNo_;

    bool vpiPackedArrayMember_;

    bool vpiConstantSelect_;

    VectorOfvariables* variables_;

    expr* expr_index_;

    VectorOfvar_bit* var_bits_;

  };

  class struct_varFactory {
  friend Serializer;
  public:
  static struct_var* make() {
    struct_var* obj = new struct_var();
    objects_.push_back(obj);
    return obj;
  }
  private:
    static std::vector<struct_var*> objects_;
  };
 	      
  class VectorOfstruct_varFactory {
  friend Serializer;
  public:
  static std::vector<struct_var*>* make() {
    std::vector<struct_var*>* obj = new std::vector<struct_var*>();
    objects_.push_back(obj);
    return obj;
  }
  private:
  static std::vector<std::vector<struct_var*>*> objects_;
  };

};

#endif

