/*
 Do not modify, auto-generated by model_gen.tcl

 Copyright 2019 Alain Dargelas

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

/*
 * File:   <CLASSNAME>.h
 * Author:
 *
 * Created on December 14, 2019, 10:03 PM
 */

#include <string>
#include <vector>
#ifndef UHDM_H
#define UHDM_H
#include "include/sv_vpi_user.h"
#include "include/vhpi_user.h"
#include "include/vpi_uhdm.h"
#include "headers/containers.h"

#define uhdmprocess 2109
#define uhdmproperty_decl 2110
#define uhdmsequence_decl 2111
#define uhdmconcurrent_assertion 2112
#define uhdmvirtual_interface_var 2113
#define uhdmlet_decl 2114
#define uhdmstmt 2115
#define uhdmscope 2116
#define uhdmconcurrent_assertions 2117
#define uhdmvariables 2118
#define uhdmparameters 2119
#define uhdmscopes 2120
#define uhdmtypespecs 2121
#define uhdmproperty_decls 2122
#define uhdmsequence_decls 2123
#define uhdmnamed_events 2124
#define uhdmnamed_event_arrays 2125
#define uhdmvirtual_interface_vars 2126
#define uhdmlogic_var 2127
#define uhdmarray_var 2128
#define uhdmarray_var_mem 2129
#define uhdmlet_decls 2130
#define uhdminstance_items 2131
#define uhdmbegin 2132
#define uhdmstmts 2133
#define uhdmnamed_begin 2134
#define uhdmstmts 2133
#define uhdmnamed_fork 2135
#define uhdmstmts 2133
#define uhdmfork_stmt 2136
#define uhdmstmts 2133
#define uhdmfor_stmt 2137
#define uhdmforeach_stmt 2138
#define uhdmgen_scope 2139
#define uhdmexpr_dist 2140
#define uhdmexpr 2141
#define uhdmdistribution 2142
#define uhdmoperand_group 2143
#define uhdmoperation 2144
#define uhdmoperands 2145
#define uhdmref_obj 2146
#define uhdmports 2147
#define uhdmtypespec 2148
#define uhdmactual_group 2149
#define uhdmvariables 2118
#define uhdmtask_func 2150
#define uhdmleft_expr 2151
#define uhdmright_expr 2152
#define uhdmstmt 2115
#define uhdmclass_defn 2153
#define uhdmref_obj 2146
#define uhdmio_decl 2154
#define uhdmtask 2155
#define uhdmfunction 2156
#define uhdmmodport 2157
#define uhdmio_decls 2158
#define uhdminterface 2159
#define uhdminterface_tf_decl 2160
#define uhdmtasks 2161
#define uhdmfunctions 2162
#define uhdmcont_assign 2163
#define uhdmports 2147
#define uhdmtypespecs 2121
#define uhdminstance 2164
#define uhdmmodule 2165
#define uhdmhigh_conn 2166
#define uhdmlow_conn 2167
#define uhdmport 2168
#define uhdmbits 2169
#define uhdmport_bit 2170
#define uhdmprimitive 2171
#define uhdmmod_path 2172
#define uhdmtchk 2173
#define uhdmdef_param 2174
#define uhdmrange 2175
#define uhdmudp_defn 2176
#define uhdmio_decl 2154
#define uhdmleft_expr 2151
#define uhdmright_expr 2152
#define uhdmtypespecs 2121
#define uhdminstance 2164
#define uhdmtask_func 2150
#define uhdmranges 2177
#define uhdmudp_defn 2176
#define uhdmmodule 2165
#define uhdmexpr 2141
#define uhdmalias_stmt 2178
#define uhdmclocking_block 2179
#define uhdmparam_assign 2180
#define uhdminstance_array 2181
#define uhdmexpr 2141
#define uhdmleft_expr 2151
#define uhdmright_expr 2152
#define uhdminstances 2182
#define uhdmrange 2175
#define uhdmmodules 2183
#define uhdminterface_array 2184
#define uhdmparam_assigns 2185
#define uhdmprogram_array 2186
#define uhdmmodule_array 2187
#define uhdmparam_assigns 2185
#define uhdmprimitive_array 2188
#define uhdmdelay 2189
#define uhdmprimitives 2190
#define uhdmgate_array 2191
#define uhdmswitch_array 2192
#define uhdmudp_array 2193
#define uhdmnet 2194
#define uhdmnets 2195
#define uhdmarray_net 2196
#define uhdmlogic_var 2127
#define uhdmarray_var 2128
#define uhdmnamed_event 2197
#define uhdmnamed_event_array 2198
#define uhdmparameters 2119
#define uhdmspec_param 2199
#define uhdmassertion 2200
#define uhdmtypespec 2148
#define uhdmclass_defn 2153
#define uhdmclass_typespec 2201
#define uhdmclass_obj 2202
#define uhdminstance 2164
#define uhdmtask_func 2150
#define uhdmnet 2194
#define uhdmarray_net 2196
#define uhdmassertion 2200
#define uhdmclass_defn 2153
#define uhdminstance 2164
#define uhdmprograms 2203
#define uhdmprogram_arrays 2204
#define uhdmnamed_event 2197
#define uhdmnamed_event_array 2198
#define uhdmspec_param 2199
#define uhdmmodule 2165
#define uhdminterface 2159
#define uhdmexpr_dist 2140
#define uhdminstance_array 2181
#define uhdmprocess 2109
#define uhdminterface_tf_decls 2205
#define uhdmmodports 2206
#define uhdmglobal_clocking 2207
#define uhdmdefault_clocking 2208
#define uhdmmod_paths 2209
#define uhdmcont_assigns 2210
#define uhdminterfaces 2211
#define uhdminterface_arrays 2212
#define uhdmprogram 2213
#define uhdminstance_array 2181
#define uhdmexpr_dist 2140
#define uhdmprocess 2109
#define uhdmdefault_clocking 2208
#define uhdminterfaces 2211
#define uhdminterface_arrays 2212
#define uhdmcont_assigns 2210
#define uhdmclocking_blocks 2214
#define uhdmpackage 2215
#define uhdmmodule 2165
#define uhdmexpr_dist 2140
#define uhdminstance_array 2181
#define uhdmprocess 2109
#define uhdmprimitives 2190
#define uhdmprimitive_arrays 2216
#define uhdmglobal_clocking 2207
#define uhdmdefault_clocking 2208
#define uhdmmodule_array 2187
#define uhdmports 2147
#define uhdminterfaces 2211
#define uhdminterface_arrays 2212
#define uhdmcont_assigns 2210
#define uhdmmodules 2183
#define uhdmmodule_arrays 2217
#define uhdmmod_paths 2209
#define uhdmtchks 2218
#define uhdmdef_params 2219
#define uhdmio_decls 2158
#define uhdmalias_stmts 2220
#define uhdmclocking_blocks 2214
#define uhdmdesign 2221
#define uhdmallModules 2222
#define uhdmtopModules 2223
#define uhdmallPrograms 2224
#define uhdmallPackages 2225


#include "headers/process.h"
#include "headers/property_decl.h"
#include "headers/sequence_decl.h"
#include "headers/concurrent_assertion.h"
#include "headers/virtual_interface_var.h"
#include "headers/let_decl.h"
#include "headers/stmt.h"
#include "headers/instance_item.h"
#include "headers/scope.h"
#include "headers/begin.h"
#include "headers/named_begin.h"
#include "headers/named_fork.h"
#include "headers/fork_stmt.h"
#include "headers/for_stmt.h"
#include "headers/foreach_stmt.h"
#include "headers/gen_scope.h"
#include "headers/expr_dist.h"
#include "headers/expr.h"
#include "headers/distribution.h"
#include "headers/operand_group.h"
#include "headers/operation.h"
#include "headers/actual_group.h"
#include "headers/ref_obj.h"
#include "headers/variables.h"
#include "headers/task_func.h"
#include "headers/task.h"
#include "headers/function.h"
#include "headers/modport.h"
#include "headers/interface_tf_decl.h"
#include "headers/cont_assign.h"
#include "headers/expr_ref_obj_group.h"
#include "headers/ports.h"
#include "headers/port.h"
#include "headers/port_bit.h"
#include "headers/primitive.h"
#include "headers/mod_path.h"
#include "headers/tchk.h"
#include "headers/def_param.h"
#include "headers/range.h"
#include "headers/udp_defn.h"
#include "headers/ref_obj_interf_net_var_group.h"
#include "headers/io_decl.h"
#include "headers/alias_stmt.h"
#include "headers/clocking_block.h"
#include "headers/param_assign.h"
#include "headers/instance_array.h"
#include "headers/interface_array.h"
#include "headers/program_array.h"
#include "headers/module_array.h"
#include "headers/primitive_array.h"
#include "headers/gate_array.h"
#include "headers/switch_array.h"
#include "headers/udp_array.h"
#include "headers/net.h"
#include "headers/nets.h"
#include "headers/array_net.h"
#include "headers/logic_var.h"
#include "headers/array_var.h"
#include "headers/named_event.h"
#include "headers/named_event_array.h"
#include "headers/parameters.h"
#include "headers/spec_param.h"
#include "headers/assertion.h"
#include "headers/typespec.h"
#include "headers/class_defn.h"
#include "headers/class_typespec.h"
#include "headers/class_obj.h"
#include "headers/instance.h"
#include "headers/interface.h"
#include "headers/program.h"
#include "headers/package.h"
#include "headers/module.h"
#include "headers/design.h"


#endif

