/*
 Do not modify, auto-generated by model_gen.tcl

 Copyright 2019 Alain Dargelas

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

/*
 * File:   <CLASSNAME>.h
 * Author:
 *
 * Created on December 14, 2019, 10:03 PM
 */

#include <string>
#include <vector>
#ifndef UHDM_H
#define UHDM_H
#include "include/sv_vpi_user.h"
#include "include/vhpi_user.h"
#include "include/vpi_uhdm.h"
#include "headers/containers.h"

#define uhdmprocess 2033
#define uhdmscope 2034
#define uhdmtask 2035
#define uhdmfunction 2036
#define uhdmmodport 2037
#define uhdmio_decls 2038
#define uhdminterface 2039
#define uhdminterface_tf_decl 2040
#define uhdmtasks 2041
#define uhdmfunctions 2042
#define uhdminterface 2039
#define uhdmprocess 2033
#define uhdminterface_tf_decls 2043
#define uhdmmodports 2044
#define uhdmglobal_clocking 2045
#define uhdmdefault_clocking 2046
#define uhdmmod_paths 2047
#define uhdmcont_assigns 2048
#define uhdminterfaces 2049
#define uhdminterface_arrays 2050
#define uhdminterface_array 2051
#define uhdmcont_assign 2052
#define uhdmport 2053
#define uhdmmodule_array 2054
#define uhdmprimitive 2055
#define uhdmprimitive_array 2056
#define uhdmmod_path 2057
#define uhdmtchk 2058
#define uhdmdef_param 2059
#define uhdmio_decl 2060
#define uhdmalias_stmt 2061
#define uhdmclocking_block 2062
#define uhdminstance_array 2063
#define uhdmmodule 2064
#define uhdminstance_array 2063
#define uhdmscope 2034
#define uhdmprocess 2033
#define uhdmprimitives 2065
#define uhdmprimitive_arrays 2066
#define uhdmglobal_clocking 2045
#define uhdmdefault_clocking 2046
#define uhdmports 2067
#define uhdminterfaces 2049
#define uhdminterface_arrays 2050
#define uhdmcont_assigns 2048
#define uhdmmodules 2068
#define uhdmmodule_arrays 2069
#define uhdmmod_paths 2047
#define uhdmtchks 2070
#define uhdmdef_params 2071
#define uhdmio_decls 2038
#define uhdmalias_stmts 2072
#define uhdmclocking_blocks 2073
#define uhdmprogram 2074
#define uhdminstance_array 2063
#define uhdmprocess 2033
#define uhdmdefault_clocking 2046
#define uhdminterfaces 2049
#define uhdminterface_arrays 2050
#define uhdmcont_assigns 2048
#define uhdmclocking_blocks 2073
#define uhdmdesign 2075
#define uhdmallModules 2076
#define uhdmtopModules 2077
#define uhdmallPrograms 2078


#include "headers/process.h"
#include "headers/scope.h"
#include "headers/task.h"
#include "headers/function.h"
#include "headers/modport.h"
#include "headers/interface_tf_decl.h"
#include "headers/interface.h"
#include "headers/interface_array.h"
#include "headers/cont_assign.h"
#include "headers/port.h"
#include "headers/module_array.h"
#include "headers/primitive.h"
#include "headers/primitive_array.h"
#include "headers/mod_path.h"
#include "headers/tchk.h"
#include "headers/def_param.h"
#include "headers/io_decl.h"
#include "headers/alias_stmt.h"
#include "headers/clocking_block.h"
#include "headers/instance_array.h"
#include "headers/module.h"
#include "headers/program.h"
#include "headers/design.h"


#endif

