/*
 Do not modify, auto-generated by model_gen.tcl

 Copyright 2019 Alain Dargelas

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

/*
 * File:   var_bit.h
 * Author:
 *
 * Created on December 14, 2019, 10:03 PM
 */

#ifndef VAR_BIT_H
#define VAR_BIT_H

namespace UHDM {

  class var_bit : public variables {
  public:
    // Implicit constructor used to initialize all members,
    // comment: var_bit();
    ~var_bit() final {}
    
    BaseClass* get_vpiParent() const { return vpiParent_; }

    bool set_vpiParent(BaseClass* data) { vpiParent_ = data; return true;}

    unsigned int get_uhdmParentType() const { return uhdmParentType_; }

    bool set_uhdmParentType(unsigned int data) { uhdmParentType_ = data; return true;}

    std::string get_vpiFile() const { return SymbolFactory::getSymbol(vpiFile_); }

    bool set_vpiFile(std::string data) { vpiFile_ = SymbolFactory::make(data); return true; }

    unsigned int get_vpiLineNo() const { return vpiLineNo_; }

    bool set_vpiLineNo(unsigned int data) { vpiLineNo_ = data; return true;}

    bool get_vpiConstantSelect() const { return vpiConstantSelect_; }

    bool set_vpiConstantSelect(bool data) { vpiConstantSelect_ = data; return true;}

    expr* get_expr_index() const { return expr_index_; }

    bool set_expr_index(expr* data) { expr_index_ = data; return true;}

    VectorOfexpr* get_expr_indexes() const { return expr_indexes_; }

    bool set_expr_indexes(VectorOfexpr* data) { expr_indexes_ = data; return true;}

    unsigned int get_vpiType() { return vpiVarBit; }

    virtual unsigned int getUhdmType() { return uhdmvar_bit; }   
  private:
    
    BaseClass* vpiParent_;

    unsigned int uhdmParentType_;

    unsigned int vpiFile_;

    unsigned int vpiLineNo_;

    bool vpiConstantSelect_;

    expr* expr_index_;

    VectorOfexpr* expr_indexes_;

  };

  class var_bitFactory {
  friend Serializer;
  public:
  static var_bit* make() {
    var_bit* obj = new var_bit();
    objects_.push_back(obj);
    return obj;
  }
  private:
    static std::vector<var_bit*> objects_;
  };
 	      
  class VectorOfvar_bitFactory {
  friend Serializer;
  public:
  static std::vector<var_bit*>* make() {
    std::vector<var_bit*>* obj = new std::vector<var_bit*>();
    objects_.push_back(obj);
    return obj;
  }
  private:
  static std::vector<std::vector<var_bit*>*> objects_;
  };

};

#endif

