/*
 Do not modify, auto-generated by model_gen.tcl

 Copyright 2019 Alain Dargelas

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

/*
 * File:   variable_loads.h
 * Author:
 *
 * Created on December 14, 2019, 10:03 PM
 */

#ifndef VARIABLE_LOADS_H
#define VARIABLE_LOADS_H

namespace UHDM {

  class variable_loads : public BaseClass {
  public:
    // Implicit constructor used to initialize all members,
    // comment: variable_loads();
    ~variable_loads()  {}
    
    virtual unsigned int getUhdmType() { return uhdmvariable_loads; }   
  private:
    
  };

  class variable_loadsFactory {
  friend Serializer;
  public:
  static variable_loads* make() {
    variable_loads* obj = new variable_loads();
    objects_.push_back(obj);
    return obj;
  }
  private:
    static std::vector<variable_loads*> objects_;
  };
 	      
  class VectorOfvariable_loadsFactory {
  friend Serializer;
  public:
  static std::vector<variable_loads*>* make() {
    std::vector<variable_loads*>* obj = new std::vector<variable_loads*>();
    objects_.push_back(obj);
    return obj;
  }
  private:
  static std::vector<std::vector<variable_loads*>*> objects_;
  };

};

#endif

