// -*- c++ -*-

/*
 Do not modify, auto-generated by cloner.py

 Copyright 2019 Alain Dargelas

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

/*
 * File:   Cloner.h
 * Author: hs
 *
 * Created on July 14, 2023, 00:00 AM
 */
#ifndef UHDM_CLONER_H
#define UHDM_CLONER_H

#include <uhdm/RTTI.h>
#include <uhdm/Serializer.h>
#include <uhdm/containers.h>

#include <map>

namespace uhdm {
// Three different variants of Cloning
//
// Cloner:
//   * Default implementation where every node in the graph gets duplicated.
//   * Nodes are cloned based on the number of times they are referenced.
//   * Number of nodes in cloned graph are likely to be greater then
//     the input graph.
// PassThroughCloner:
//   * This is opposite of the default cloner where none of the nodes
//     are duplicated.
//   * As such, this implementation is of no practical use but can be used
//     as a base where only certain nodes need to be duplicated.
// MirrorCloner:
//   * This generates an exact clone of the input graph.

class Cloner : public RTTI {
  UHDM_IMPLEMENT_RTTI(Cloner, RTTI)

 protected:
  using callstack_t = std::vector<const Any *>;

 public:
  explicit Cloner(Serializer *serializer) : m_serializer(serializer) {}
  virtual ~Cloner() = default;
  Cloner(const Cloner &rhs) = delete;
  Cloner &operator=(const Cloner &rhs) = delete;

  Serializer *getSerializer() { return m_serializer; }

  template <typename T>
  T *clone(const T *source, Any *parent) {
    return static_cast<T *>(cloneAny(static_cast<const Any *>(source), parent));
  }

 private:
  template <typename T>
  T *cloneT(const T *source, Any *parent);

 protected:
  template <typename T>
  std::vector<T *> *cloneT(const std::vector<T *> *source);

  template <typename T>
  std::vector<T *> *cloneT(const std::vector<T *> *source, Any *parent);

  virtual Any *cloneAny(const Any *source, Any *parent);

  // clang-format off
  virtual void copy(const Any* source, Any* target);
//<COPY_DECLARATIONS>
  // clang-format on

  // clang-format off
  virtual Any* clone(const Any* source, Any* parent);
//<CLONE_ANY_DECLARATIONS>
  // clang-format on

  // clang-format off
  virtual AnyCollection* clone(const AnyCollection* source, Any* parent);
//<CLONE_MANY_DECLARATIONS>
  // clang-format on

 protected:
  Serializer *const m_serializer = nullptr;
  callstack_t m_callstack;
};

template <typename T>
inline std::vector<T *> *Cloner::cloneT(const std::vector<T *> *source) {
  if ((source == nullptr) || source->empty()) return nullptr;
  std::vector<T *> *const target = m_serializer->template makeCollection<T>();
  target->insert(target->cend(), source->cbegin(), source->cend());
  return target;
}

template <typename T>
inline std::vector<T *> *Cloner::cloneT(const std::vector<T *> *source,
                                        Any *parent) {
  if ((source == nullptr) || source->empty()) return nullptr;
  std::vector<T *> *const target = m_serializer->template makeCollection<T>();
  target->reserve(source->size());
  const std::vector<T *> collection(*source);
  for (T *obj : collection) {
    target->emplace_back(
        static_cast<T *>(cloneAny(static_cast<const Any *>(obj), parent)));
  }
  return target;
}

class PassThroughCloner : public Cloner {
  UHDM_IMPLEMENT_RTTI(PassThroughCloner, Cloner)

 public:
  explicit PassThroughCloner(Serializer *serializer) : Cloner(serializer) {}
  ~PassThroughCloner() override = default;
  PassThroughCloner(const PassThroughCloner &rhs) = delete;
  PassThroughCloner &operator=(const PassThroughCloner &rhs) = delete;

  using Cloner::clone;

 protected:
  Any *cloneAny(const Any *source, Any *parent) override;

  // clang-format off
  AnyCollection* clone(const AnyCollection* source, Any* parent) override { return const_cast<AnyCollection *>(source); }
//<PASSTHROUGHCLONER_MANY_DECLARATIONS>
  // clang-format on
};

class MirrorCloner : public Cloner {
  UHDM_IMPLEMENT_RTTI(MirrorCloner, Cloner)

 public:
  explicit MirrorCloner(Serializer *serializer) : Cloner(serializer) {}
  ~MirrorCloner() override = default;
  MirrorCloner(const MirrorCloner &rhs) = delete;
  MirrorCloner &operator=(const MirrorCloner &rhs) = delete;

  using Cloner::clone;

 protected:
  Any *cloneAny(const Any *source, Any *parent) override;

 protected:
  using cloned_t = std::map<const Any *, Any *>;
  cloned_t m_cloned;
};
}  // namespace uhdm

UHDM_IMPLEMENT_RTTI_CAST_FUNCTIONS(cloner_cast, uhdm::Cloner)
#endif  // UHDM_CLONER_H
