/*
 Do not modify, auto-generated by model_gen.tcl

 Copyright 2019 Alain Dargelas

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

/*
 * File:   Serializer.cpp
 * Author:
 *
 * Created on December 14, 2019, 10:03 PM
 */

#include <vector>
#include <map>
typedef void any;
#include "headers/containers.h"
#include "headers/uhdm.h"
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <unistd.h>
#include "UHDM.capnp.h"
#include <capnp/message.h>
#include <capnp/serialize-packed.h>
#include <iostream>


using namespace UHDM;

std::vector<uhdm_handle*> uhdm_handleFactory::objects_;

Id2SymbolMap SymbolFactory::id2SymbolMap_;

Symbol2IdMap SymbolFactory::symbol2IdMap_;

unsigned int SymbolFactory::idCounter_ = 0;

unsigned int SymbolFactory::Make(const std::string& symbol) {
  Symbol2IdMap::iterator itr = symbol2IdMap_.find(symbol);
  if (itr == symbol2IdMap_.end()) {
    symbol2IdMap_.insert(std::make_pair(symbol, idCounter_));
    id2SymbolMap_.push_back(symbol);
    idCounter_++;
    unsigned int tmp = idCounter_ - 1;
    return (tmp);
  } else {
    unsigned int tmp = (*itr).second;
    return tmp;
  }
}

std::string SymbolFactory::bad_symbol_ = "@@BAD_SYMBOL@@";

const std::string& SymbolFactory::GetSymbol(unsigned int id) {
   if (id >= id2SymbolMap_.size())
    return bad_symbol_;
  return id2SymbolMap_[id];
}

unsigned int SymbolFactory::GetId(const std::string& symbol) {
   Symbol2IdMap::iterator itr = symbol2IdMap_.find(symbol);
  if (itr == symbol2IdMap_.end()) {
    return 0;
  } else {
    unsigned int tmp = (*itr).second;
    return tmp;
  }
}
 
