/*
  Do not modify, auto-generated by model_gen.tcl

  Copyright 2019 Alain Dargelas

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
*/

/*
 * File:   SymbolFactory.cpp
 * Author:
 *
 * Created on December 14, 2019, 10:03 PM
 */
#include <uhdm/SymbolFactory.h>

namespace UHDM {

static constexpr SymbolFactory::ID kBadId = -1;  // setting all the bits.
static const std::string kBadSymbol = "@@BAD_SYMBOL@@";

SymbolFactory::ID SymbolFactory::Make(const std::string& symbol) {
  const auto inserted = symbol2IdMap_.insert({symbol, idCounter_});
  if (inserted.second) {
    id2SymbolMap_.emplace_back(symbol);
    idCounter_++;
  }
  return inserted.first->second;
}

const std::string& SymbolFactory::GetSymbol(ID id) const {
  return (id < id2SymbolMap_.size()) ? id2SymbolMap_[id] : kBadSymbol;
}

SymbolFactory::ID SymbolFactory::GetId(const std::string& symbol) const {
  auto found = symbol2IdMap_.find(symbol);
  return (found == symbol2IdMap_.end()) ? kBadId : found->second;
}

}  // namespace UHDM
