/*
 Do not modify, auto-generated by script

 Copyright 2019-2020 Alain Dargelas

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

/*
 * File:   UhdmVisitor.cpp
 * Author: hs
 *
 * Created on October 01, 2025, 00:00 AM
 */
#include <uhdm/UhdmVisitor.h>
#include <uhdm/uhdm.h>

// System headers
#include <map>

namespace uhdm {
bool UhdmVisitor::didVisitAll(const Serializer& serializer) const {
  const Serializer::IdMap idMap = serializer.getAllObjects();

  AnySet allObjects;
  std::transform(
      idMap.cbegin(), idMap.cend(),
      std::inserter(allObjects, allObjects.begin()),
      [](std::map<const BaseClass*, uint32_t>::const_reference entry) {
        return entry.first;
      });

  AnySet diffObjects;
  std::set_difference(allObjects.begin(), allObjects.end(), m_visited.begin(),
                      m_visited.end(),
                      std::inserter(diffObjects, diffObjects.begin()));

  return diffObjects.empty();
}

void UhdmVisitor::visitAny_(const Any* object) {
  // NOTE(HS): Don't walk upwards. When initiating calls from non-design
  // objects, the intended behavior is to walk the subtree but enabling
  // this walks the entire deisgn.
  // if (const Any* const parent = object->getParent()) {
  //   listenAny(parent, vpiParent);
  // }
}

// clang-format off
// <UHDMVISITOR_PRIVATE_VISIT_IMPLEMENTATIONS>
// clang-format on

void UhdmVisitor::visit(const Any* object) {
  if (m_abortRequested) return;
  if (!m_visited.emplace(object).second) return;

  visitAny(object);

  // clang-format off
  switch (object->getUhdmType()) {
// <UHDMVISITOR_VISIT_ANY_CASE_STATEMENTS>
    default: break;
  }
  // clang-format on
}

} // namespace uhdm
