/*
 Do not modify, auto-generated by model_gen.tcl

 Copyright 2019-2020 Alain Dargelas

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

/*
 * File:   vpi_listener.cpp
 * Author:
 *
 * Created on December 14, 2019, 10:03 PM
 */

#include <string.h>

#include <iostream>
#include <map>
#include <string>
#include <vector>

#include "include/sv_vpi_user.h"
#include "include/vhpi_user.h"

#include "headers/uhdm_types.h"
#include "headers/containers.h"
#include "headers/vpi_uhdm.h"
#include "headers/uhdm.h"
#include "headers/Serializer.h"
#include "headers/vpi_listener.h"

using namespace UHDM;

static vpiHandle NewHandle (UHDM_OBJECT_TYPE type, const void *object) {
  return reinterpret_cast<vpiHandle>(new uhdm_handle(type, object));
}

<VPI_LISTENERS>

void listen_any(vpiHandle object, VpiListener* listener) {
}

void listen_designs (const std::vector<vpiHandle>& designs, VpiListener* listener) {
  for (auto design_h : designs) {
    listen_design(design_h, listener);
  }
}

