/*
 Do not modify, auto-generated by model_gen.tcl

 Copyright 2019 Alain Dargelas

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

/*
 * File:   instance_item.cpp
 * Author:
 *
 * Created on December 14, 2019, 10:03 PM
 */


#include <iostream>
#include "headers/uhdm.h"
#include "instance_item.h"

namespace UHDM {

  bool instance_itemGroupCompliant(any* item) {
    BaseClass* the_item = (BaseClass*) item;
    unsigned int uhdmtype = the_item->getUhdmType();
    if ((uhdmtype != uhdmtask_func) && (uhdmtype != uhdmfunction) && (uhdmtype != uhdmtask) && (uhdmtype != uhdmnet) && (uhdmtype != uhdmlogic_net) && (uhdmtype != uhdmpacked_array_net) && (uhdmtype != uhdmstruct_net) && (uhdmtype != uhdmenum_net) && (uhdmtype != uhdminteger_net) && (uhdmtype != uhdmtime_net) && (uhdmtype != uhdmarray_net) && (uhdmtype != uhdmvariables) && (uhdmtype != uhdmchandle_var) && (uhdmtype != uhdmbyte_var) && (uhdmtype != uhdmstruct_var) && (uhdmtype != uhdmenum_var) && (uhdmtype != uhdmshort_real_var) && (uhdmtype != uhdminteger_var) && (uhdmtype != uhdmstring_var) && (uhdmtype != uhdmshort_int_var) && (uhdmtype != uhdmtime_var) && (uhdmtype != uhdmint_var) && (uhdmtype != uhdmreal_var) && (uhdmtype != uhdmlogic_var) && (uhdmtype != uhdmpacked_array_var) && (uhdmtype != uhdmarray_var) && (uhdmtype != uhdmclass_var) && (uhdmtype != uhdmunion_var) && (uhdmtype != uhdmlong_int_var) && (uhdmtype != uhdmbit_var) && (uhdmtype != uhdmvar_bit) && (uhdmtype != uhdmparameters) && (uhdmtype != uhdmassertion) && (uhdmtype != uhdmtypespec) && (uhdmtype != uhdmclass_defn) && (uhdmtype != uhdmprogram) && (uhdmtype != uhdmprogram_array) && (uhdmtype != uhdmlogic_var) && (uhdmtype != uhdmarray_var) && (uhdmtype != uhdmnamed_event) && (uhdmtype != uhdmnamed_event_array) && (uhdmtype != uhdmspec_param)) {
      std::cout << "Internal Error: adding wrong object type (" << getUhdmName(uhdmtype) << ") in a instance_item group!\n";   
      return false;
    }
    return true;
  }

  bool instance_itemGroupCompliant(VectorOfany* vec) {
    for (auto item : *vec) {
      if (!instance_itemGroupCompliant(item)) {
	return false;
      }
    }
    return true;
  }
 	     
};

